domains:
- name: bootstrap
  resolvers:
  - {id: domain_fragments, type: multi-document-retrieval, files: [
        domain-bootstrap.md]}
  renders:
  - name: bootstrap
    resolvers:
    - {id: prompt_fragments, type: multi-document-retrieval, files: [
          bootstrap-instructions.pfrag, backlog.cdoc]}
    - {id: repo_content, type: repo_content, includes: [.], excludes: [.clanker],
      sorting: normal}                                                                                             #".git" to excludes. should make includes existence obligatory, but non-existent excludes are ok
